server:
  port: 5577

spring:
  activemq:
    broker-url: tcp://192.168.1.235:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true      # false = queue    true =  topic


myTopic: boot-activemq-topic



